### PR TITLE
Add the CategoryAttribute data type

### PR DESCRIPTION
**Pull request by danbeck**
This pull requests adds the CategoryAttribute data type. It extends the GraphQL schema to retrieve category attributes as follows:

```
query {
    categories(filter:{
        title:{
            equals: "test"
        }
    }) {       
        id
        title
        longDescription
        thumbnail
        root {
            id
        }
        seo {
            description
            url
        }
        attributes {
                attribute{
                    title
                }
                values
        }
    }
} 
```

Notice: The DataType Attribute was changed too, because attribute->getRawFieldData('oxtitle') returns null for categories: https://github.com/OXID-eSales/graphql-storefront-module/compare/b-6.5.x...danbeck:graphql-storefront-module:b-6.5.x?expand=1#diff-53162643b996768dd58dba6a7664e935810b8103631e3357070a121cd7afeccfR40

### CODE REVIEW

**Comment by danbeck** [comment]
The code now complies to the code style guidelines.

**Comment by danbeck** [comment]
Hi @Sieg @hkreuter, could you provide some feedback to this pull request? Must something be changed?

**Comment by Sieg** [comment]
Hi @danbeck! Yah, the functionality looks promising, but tests are missing, so this PR is waiting while we will have time to write some tests here. If you can add them, it would help a lot.

**Comment by Sieg** [comment]
Hi @danbeck, sorry it took longer than expected, but we have everything merged now to our b-7.0.x branch. Thanks for the improvement!

**Pull request merged**
